// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqW5bTXp5KyGMrqGmLk-4N8TBu65YQvuA',
    appId: '1:898365649245:web:9553189274a6c8b5ad78b4',
    messagingSenderId: '898365649245',
    projectId: 'smart-energy-96190',
    authDomain: 'smart-energy-96190.firebaseapp.com',
    databaseURL: 'https://smart-energy-96190-default-rtdb.firebaseio.com',
    storageBucket: 'smart-energy-96190.appspot.com',
    measurementId: 'G-26BRHPJMYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTLNZ0S0aHfrJB6V2UGSKhxdfHdwR-Qcs',
    appId: '1:898365649245:android:7855293e8cbcfdccad78b4',
    messagingSenderId: '898365649245',
    projectId: 'smart-energy-96190',
    databaseURL: 'https://smart-energy-96190-default-rtdb.firebaseio.com',
    storageBucket: 'smart-energy-96190.appspot.com',
  );
}
